#### Variables
@farmer1Id = 5f2f08739dfcd4496c3f2796
@farmer2Id = 5f2f0e5a3508017380fea569
@productId = 5f2f14e137134d3e980faa34
@farmerOrder1Id = 5f3253144dd9038a8cf7b2e4
@farmerOrder2Id = 5f30ed94144ed62fcc90d14f
@customerId = 5f2f080f9dfcd4496c3f2794
@customerOrderId = 5f3083702777901b8c6425b1
@cartOrderId = 5f321287eacf393f7c36ab1b

#### Signup a farmer
POST http://localhost:3000/account/signup HTTP/1.1
Content-Type: application/json

{"email":"sam@test.com", "password":"123"}

#### Signin a farmer
POST http://localhost:3000/account/signin/ HTTP/1.1
Content-Type: application/json

{
  "email": "sam@test.com", 
  "password": "123"
  }

#### Signup a customer
POST http://localhost:3000/customers/signup HTTP/1.1
Content-Type: application/json

{
  "email": "customer@test.com",
  "password": "123",
  "fullName": {
    "fisrtName": "Customer", 
    "lastName": "Test"
  }, 
  "address": { 
    "street": "1000N 4th st", 
    "city" : "fairfield", 
    "state": "Iowa", 
    "zipcode": "12345"
  },
  "phone": "1234567"
}

#### Signin a customer
POST http://localhost:3000/customers/signin/ HTTP/1.1
Content-Type: application/json

{ 
  "email": "customer@test.com", 
  "password": "123"
}

#### Signup another farmer
POST http://localhost:3000/farmers/signup HTTP/1.1
Content-Type: application/json

{
  "email": "farmer@test.com",
  "password": "123",
  "fullName": {
    "fisrtName": "Farmer", 
    "lastName":"Test"
  }, 
  "address": { 
    "street": "1000N 4th st", 
    "city" : "fairfield", 
    "state": "Iowa", 
    "zipcode": "12345"
  },
  "phone": "1234567", 
  "rate": 4
}

#### Farmer signin
POST http://localhost:3000/farmers/signin/ HTTP/1.1
Content-Type: application/json

{
  "email": "farmer@test.com", 
  "password": "123"
}

#### Farmer signup
POST http://localhost:3000/farmers/signup HTTP/1.1
Content-Type: application/json

{
  "email": "ema@test.com",
  "password": "123",
  "fullName": {
      "fisrtName": "Ema", 
      "lastName": "Kihshen"
  }, 
  "address": { 
      "street": "1000N 4th St", 
      "city" : "Fairfield", 
      "state": "IA", 
      "zipcode": "56789"
  },
  "phone": "1234567", 
  "rate": 4
}

#### Farmer signin
POST http://localhost:3000/farmers/signin/ HTTP/1.1
Content-Type: application/json

{
  "email": "sam6@test.com", 
  "password": "123"
}

#### Get a list of all farmers
GET http://localhost:3000/farmers/ HTTP/1.1

#### Get a farmer by Id
GET http://localhost:3000/farmers/{{farmer1Id}} HTTP/1.1

#### Get a farmer by Id
GET http://localhost:3000/farmers/{{farmer2Id}} HTTP/1.1

### For testing purposes only
# #### Rating a farmer - Excellent
# POST http://localhost:3000/farmers/{{farmer2Id}}/rate/Excellent HTTP/1.1

# #### Rating a farmer - Good
# POST http://localhost:3000/farmers/{{farmer2Id}}/rate/Good HTTP/1.1

# #### Rating a farmer - Bad
# POST http://localhost:3000/farmers/{{farmer2Id}}/rate/Bad HTTP/1.1

#### Add a product
POST http://localhost:3000/farmers/{{farmer2Id}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "Apple",
    "description": "Californian apple",
    "price": 4.50,
    "pic": "picture url",
    "catagory": "Fruit",
    "quantity": 25,
    "pushing_date": "08-08-2020"
  }

#### Add another product
POST http://localhost:3000/farmers/{{farmer2Id}}/products HTTP/1.1
Content-Type: application/json

{
    "name": "Lettuce",
    "description": "Green leafy",
    "price": 2.50,
    "pic": "picture url",
    "catagory": "Vegetable",
    "quantity": 5,
    "pushing_date": "0-09-2020"
  }

#### Get all products (Farmer with no products yet)
GET http://localhost:3000/farmers/{{farmer1Id}}/products HTTP/1.1

#### Get all products
GET http://localhost:3000/farmers/{{farmer2Id}}/products HTTP/1.1

#### Increase product quantity by one
PATCH http://localhost:3000/farmers/{{farmer2Id}}/products/{{productId}}/inc HTTP/1.1

#### Decrease product quantity by one
PATCH http://localhost:3000/farmers/{{farmer2Id}}/products/{{productId}}/dec HTTP/1.1

#### Remove a product
DELETE http://localhost:3000/farmers/{{farmer2Id}}/products/{{productId}} HTTP/1.1

#### Add order to farmer (To be called from Customer controller addOrder method)
POST http://localhost:3000/farmers/{{farmer2Id}}/orders HTTP/1.1
Content-Type: application/json

{
    "oderdingDate": "08-08-2020",
    "deliveryDate": "08-12-2020",
    "farmerId": "5f30d8f578e2278c947aacd9",
    "productId": "f30db8d78e2278c947aacdc",
    "status": "pending",
    "price": 4.50,
    "quantity": 25,
    "totalPrice": 4.50,
    "paidStatus": "pending",
    "ratedStatus":false
  }

#### Get all orders [should be sorted by ... Date descending?]
GET http://localhost:3000/farmers/{{farmer2Id}}/orders HTTP/1.1

#### Cancelling an order by a farmer
DELETE http://localhost:3000/farmers/{{farmer2Id}}/orders/{{farmerOrder1Id}} HTTP/1.1

#### Change order status to Ready (can also be sent through req.params.<>)
PATCH http://localhost:3000/farmers/{{farmer2Id}}/orders/{{farmerOrder2Id}} HTTP/1.1
Content-Type: application/json

{
  "status": "Ready"
}

#### Change order status to Complete
PATCH http://localhost:3000/farmers/{{farmer2Id}}/orders/{{farmerOrder2Id}} HTTP/1.1
Content-Type: application/json

{
  "status": "Complete"
}

### Get all customers (Can be used by the SuperUser)
GET http://localhost:3000/customers HTTP/1.1

### Get all orders for a customer
GET http://localhost:3000/customers/{{customerId}}/orders HTTP/1.1

### Get all orders for a customer filtered by status and sorted by date
GET http://localhost:3000/customers/{{customerId}}/orders/pending HTTP/1.1

#### Add/Make order to a customer
POST http://localhost:3000/customers/{{customerId}}/orders HTTP/1.1
Content-Type: application/json

{
  "oderdingDate": "08-08-2020",
  "deliveryDate": "08-12-2020",
  "farmerId": "5f2f0e5a3508017380fea569",
  "productId": "5f2f14e137134d3e980faa34",
  "status": "pending",
  "price": 4.50,
  "quantity": 25,
  "totalPrice": 4.50,
  "paidStatus": "pending",
  "ratedStatus": false
}

### Cancel customer orders
DELETE  http://localhost:3000/customers/{{customerId}}/orders/{{customerOrderId}} HTTP/1.1

### Get customer's shoping cart
GET http://localhost:3000/customers/{{customerId}}/cart HTTP/1.1

### Add an order to shoping cart
POST http://localhost:3000/customers/{{customerId}}/cart HTTP/1.1
Content-Type: application/json

{
  "oderdingDate": "08-08-2020",
  "deliveryDate": "08-12-2020",
  "farmerId": "5f2f0e5a3508017380fea569",
  "productId": "5f2f14e137134d3e980faa34",
  "status": "pending",
  "price": 4.50,
  "quantity": 25,
  "totalPrice": 102.50,
  "paidStatus": "pending",
  "ratedStatus": false
}

# ### 
# PATCH http://localhost:3000/customers/{{customerId}}/cart/{{cartOrderId}} HTTP/1.1

### Adding a product to order
PATCH http://localhost:3000/customers/{{customerId}}/cart/{{productId}} HTTP/1.1

# ### 
# PATCH http://localhost:3000/customers/{{customerId}}/cart/5f3211124ae918374ce50d2a HTTP/1.1

### 
PATCH http://localhost:3000/customers/{{customerId}}/cart/{{cartOrderId}} HTTP/1.1

### 
DELETE http://localhost:3000/customers/{{customerId}}/cart/{{cartOrderId}} HTTP/1.1

### Checkout
POST http://localhost:3000/customers/{{customerId}}/checkout HTTP/1.1

### Rating a farmer
# POST http://localhost:3000/customers/{{productId}}/rate/1 HTTP/1.1
POST http://localhost:3000/customers/{{customerId}}/orders/{{customerOrderId}}/rate/1 HTTP/1.1

### Increase quantity of order in shopping cart
PATCH http://localhost:3000/customers/{{customerId}}/cart/orders/{{cartOrderId}}/inc HTTP/1.1
Content-Type: application/json

{
  "price": 10
}

### Decrease quantity of order in shopping cart
PATCH http://localhost:3000/customers/{{customerId}}/cart/orders/{{cartOrderId}}/dec HTTP/1.1
Content-Type: application/json

{
  "price": 10
}
